# Generated by Django 5.1.3 on 2024-11-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=100)),
                ('report_description', models.TextField()),
                ('report_status', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='report_area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
                ('area_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.report')),
            ],
        ),
        migrations.CreateModel(
            name='report_history',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateField()),
                ('history_description', models.TextField()),
                ('history_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='report_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.user'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateField()),
                ('comment_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.report')),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.user')),
            ],
        ),
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_name', models.CharField(max_length=100)),
                ('attachment_description', models.TextField()),
                ('attachment_date', models.DateField()),
                ('attachment_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.report')),
                ('attachment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.user')),
            ],
        ),
    ]
