# Generated by Django 5.1.3 on 2024-11-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorelServerside', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(choices=[('implantation', 'Implantação'), ('EHS', 'EHS'), ('engineering', 'Engenharia'), ('Subdiv', 'Subdiv'), ('N/A', 'N/A')], default='N/A', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='attachment_report',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_report',
        ),
        migrations.RemoveField(
            model_name='report_history',
            name='history_description',
        ),
        migrations.RemoveField(
            model_name='report_history',
            name='history_report',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report_history',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='report_history',
            name='history_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.user'),
        ),
        migrations.AddField(
            model_name='report_history',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='internal_type_user',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Employee', 'Funcionário')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Internal', 'Interno'), ('External', 'Externo')], default='Internal', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_status',
            field=models.CharField(choices=[('Open', 'Aberto'), ('Closed', 'Fechado'), ('In Progress', 'Em Andamento')], default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.area'),
        ),
        migrations.CreateModel(
            name='checklist_report',
            fields=[
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('checklist_name', models.CharField(max_length=100)),
                ('checklist_description', models.TextField()),
                ('checklist_date', models.DateField()),
                ('checklist_observation', models.TextField()),
                ('checklist_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.user')),
            ],
        ),
        migrations.DeleteModel(
            name='report_area',
        ),
    ]
