# Generated by Django 5.1.3 on 2024-11-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorelServerside', '0002_area_remove_attachment_attachment_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborType',
            fields=[
                ('labor_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('labor_type', models.CharField(choices=[('direct worker', 'Mão de Obra Direta'), ('indirect worker', 'Mão de Obra Indireta'), ('third party', 'Terceirizado')], default='direct worker', max_length=50)),
                ('labor_subtype', models.CharField(blank=True, choices=[('mechanic', 'Mecânico'), ('electrician', 'Eletricista'), ('painter', 'Pintor'), ('carpenter', 'Carpinteiro'), ('plumber', 'Encanador'), ('welder', 'Soldador'), ('bricklayer', 'Pedreiro'), ('helper', 'Ajudante'), ('installer', 'Instalador'), ('foreman', 'Mestre de Obras'), ('plasterer', 'Gesseiro'), ('laborer', 'Servente'), ('other', 'Outro'), ('engineer', 'Engenheiro'), ('technician', 'Técnico'), ('supervisor', 'Supervisor'), ('inspector', 'Inspetor'), ('safety technician', 'Técnico de Segurança'), ('architect', 'Arquiteto'), ('designer', 'Designer'), ('intern', 'Estagiário'), ('building_technician', 'Técnico de Construção'), ('other', 'Outro')], max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='afternoon_weather',
            field=models.CharField(choices=[('Sunny', 'Ensolarado'), ('Cloudy', 'Nublado'), ('Rainy', 'Chuvoso'), ('Foggy', 'Nebuloso'), ('Stormy', 'Tempestuoso')], default='Sunny', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='afternoon_work_condition',
            field=models.CharField(choices=[('Practicable', 'Praticável'), ('Partially Practicable', 'Parcialmente Praticável'), ('Unpracticable', 'Impraticável')], default='Practicable', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='reports', to='autorelServerside.attachment'),
        ),
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='reports', to='autorelServerside.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='morning_weather',
            field=models.CharField(choices=[('Sunny', 'Ensolarado'), ('Cloudy', 'Nublado'), ('Rainy', 'Chuvoso'), ('Foggy', 'Nebuloso'), ('Stormy', 'Tempestuoso')], default='Sunny', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='morning_work_condition',
            field=models.CharField(choices=[('Practicable', 'Praticável'), ('Partially Practicable', 'Parcialmente Praticável'), ('Unpracticable', 'Impraticável')], default='Practicable', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='night_weather',
            field=models.CharField(choices=[('Sunny', 'Ensolarado'), ('Cloudy', 'Nublado'), ('Rainy', 'Chuvoso'), ('Foggy', 'Nebuloso'), ('Stormy', 'Tempestuoso')], default='Sunny', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='night_work_condition',
            field=models.CharField(choices=[('Practicable', 'Praticável'), ('Partially Practicable', 'Parcialmente Praticável'), ('Unpracticable', 'Impraticável')], default='Practicable', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='report_interval_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_interval_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_work_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_work_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='labor_type',
            field=models.ManyToManyField(blank=True, related_name='reports', to='autorelServerside.labortype'),
        ),
        migrations.CreateModel(
            name='ReportActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Infra', 'Etapa de Infraestrutura'), ('Installation', 'Etapa de Instalação'), ('Final', 'Etapa de Entrega Final')], default='Infra', max_length=50)),
                ('sub_stage', models.CharField(blank=True, choices=[('Soil Survey', 'Sondagem do Terreno'), ('Trenching and Duct Laying', 'Execução de Valetamento com Lançamento de Dutos'), ('Installation of 600mm Passage Boxes', 'Instalação das Caixas de Passagem de 600mm'), ('Crossing Execution', 'Execução de Travessia'), ('Cable Laying', 'Lançamento dos Cabos'), ('Signal Installation', 'Instalação de Sinais'), ('MCH Installation', 'Instalação de MCH'), ('MCH Cable Connection', 'Ligação nos Cabos da MCH'), ('Parapet Painting', 'Pintura no Parapet'), ('Technical Delivery', 'Entrega Técnica'), ('Cleaning and Organization', 'Limpeza e Organização do Local')], max_length=50, null=True)),
                ('planned_completion_task', models.CharField(default='100%', max_length=10)),
                ('actual_completion_task', models.CharField(blank=True, max_length=10, null=True)),
                ('accumulated', models.CharField(blank=True, max_length=10, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.CharField(blank=True, max_length=10, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_activities', to='autorelServerside.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='report_activities', to='autorelServerside.reportactivities'),
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_title', models.CharField(max_length=100)),
                ('survey_location', models.CharField(max_length=100)),
                ('survey_description', models.TextField()),
                ('survey_start_date', models.DateField()),
                ('survey_end_date', models.DateField()),
                ('survey_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorelServerside.user')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='belong_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='autorelServerside.survey'),
        ),
    ]
